config/routes.rb
Rails.application.routes.draw do
  get 'books/_error'
  get 'books/edit'
  get 'books/index'
  get 'books/new'
  get 'books/show'
  get 'show_room/index'
  get 'sessions/new'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get  "/help", to: "static_pages#help"
    get  "/contact", to: "static_pages#contact"
    get  "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get  "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :hotels
    resources :rooms
    get "/show_room", to: "show_room#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :room_types
  validates :name, presence: true
  validates :starLevel, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :room_type
  has_many :comments
  validates :name, presence: true

  mount_uploader :image, ImageUploader
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  belongs_to :hotel
  has_many :rooms
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :comments

  before_save :email_downcase
  validates :fullname, presence: true,
            length: {maximum: Settings.max_length_name}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            length: {maximum: Settings.max_length_email},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :password, presence: true,
            length: {minimum: Settings.min_length_pass}

  has_secure_password

  private
  def email_downcase
    email.downcase!
  end

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception
  before_action :set_locale

  private

  def set_locale
    locale = params[:locale].to_s.strip.to_sym
    I18n.locale = if I18n.available_locales.include?(locale)
                    locale
                  else
                    I18n.default_locale
                  end
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def _error
  end

  def edit
  end

  def index
  end

  def new
  end

  def show
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :find_hotel_id, only: %i(edit show update destroy)

  def index
    @hotel = Hotel.all
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new hotel_params

    if @hotel.save
      redirect_to hotels_url
    else
      render :new
    end
  end

  def show; end

  def update
    if @hotel.update(hotel_params)
      redirect_to @hotel
    else
      render :edit
    end
  end

  def destroy
    if @hotel.destroy
      flash[:success] = t "hotel_delete"
      redirect_to hotels_url
    else
      flash[:danger] = t "delete_fail"
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit :name, :starLevel, :address, :description, :image
  end

  def find_hotel_id
    @hotel = Hotel.find_by id: params[:id]

    return if @hotel
    flash[:danger] = t "not_found"
    redirect_to root_url
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_room_id, only: %i(edit show update destroy)

  def index
    @room = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new room_params

    if @room.save
      redirect_to rooms_url
    else
      render :new
    end
  end

  def show; end

  def update
    if @room.update(room_params)
      redirect_to @room
    else
      render :edit
    end
  end

  def destroy
    if @room.destroy
      flash[:success] = t "room_delete"
      redirect_to rooms_url
    else
      flash[:danger] = t "delete_fail"
    end
  end

  private

  def room_params
    params.require(:room).permit :name, :hotel_id, :status, :room_type_id, :description, :image
  end

  def find_room_id
    @room = Room.find_by id: params[:id]

    return if @room
    flash[:danger] = t "not_found"
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = t "danger"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/show_room_controller.rb
class ShowRoomController < ApplicationController
  def index
    @id_hotel = params[:id]
    @room = Room.where(hotel_id: @id_hotel)
    # @room = Room.all

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @hotel = Hotel.all
  end

  def help; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      log_in @user
      flash[:success] = t "welcome"
      redirect_to @user
    else
      flash[:danger] = t "error_signup"
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])

    return redirect_to root_path if @user
    flash[:danger] = t "error_find_user"
    redirect_to signup_path
  end

  private

  def user_params
    params.require(:user).permit :fullname, :address, :telephone, :email,
     :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t ".hotel_ma"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/show_room_helper.rb
module ShowRoomHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/books/_error.html.erb
<h1>Books#_error</h1>
<p>Find me in app/views/books/_error.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/hotels/_error.html.erb
<% if @hotel.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "The form contains" %> <%= pluralize @hotel.errors.count, "error" %>.
    </div>
    <ul>
    <% @hotel.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<%= form_with(model: @hotel, local: true) do |form| %>
  <%= render 'error' %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name, class:"form-control" %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description, :value => @hotel.description, class:"form-control" %>
    </p>
    <p>
      <%= form.label :starLevel %><br>
      <%= form.text_field :starLevel, class:"form-control" %>
    </p>
    <p>
      <%= form.label :address %><br>
      <%= form.text_field :address, class:"form-control" %>
    </p>
    <p>
      <%= form.label :image %>
      <%= form.file_field :image %>
      <%= image_tag @hotel.image.to_s, class:'fixsize' %>
    </p>

    <p>
      <%= form.submit  "update", class: "btn btn-primary" %>
    </p>

  <% end %>
    </div>
  </div>

  <%= link_to 'Back', root_path %>

app/views/hotels/index.html.erb
<%= link_to t("new_hotel"), new_hotel_path %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= t "hotel_name" %></th>
      <th scope="col"><%= t "description" %></th>
      <th scope="col"><%= t "star_level" %></th>
      <th scope="col"><%= t "address" %></th>
      <th scope="col"><%= t "image" %></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @hotel.each do |t| %>
    <tr>
      <td><%= t.name %></td>
      <td><%= t.description %></td>
      <td><%= t.starLevel %></td>
      <td><%= t.address %></td>
      <td><%= image_tag t.image_url.to_s, class:"fixsize" %></td>
      <td>
        <%= link_to t("edit"), edit_hotel_path(t), class:"btn btn-primary" %>
        <%= link_to t("delete"), hotel_path(t), class:"btn btn-danger",
              method: :delete, data: { confirm: t("you_sure") } %>
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/hotels/new.html.erb
<!-- <div class="jumbotron">
  <p class="display text-center">New Hotel</p>
</div> -->
<% provide :title, t("new_hotel") %>
<h1><%= t "new_hotel" %></h1>
<p>
<%= form_with scope: :hotel, url: hotels_path, local: true do |form| %>
  <%= render 'error' %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <p>
      <%= form.label :name, t("name_hotel") %><br>
      <%= form.text_field :name, class:"form-control" %>
    </p>
    <p>
      <%= form.label :description, t("description") %><br>
      <%= form.text_area :description, class:"form-control"%>
    </p>
    <p>
      <%= form.label :starLevel, t("star_level") %><br>
      <%= form.text_field :starLevel, class:"form-control" %>
    </p>
    <p>
      <%= form.label :address, t("address") %><br>
      <%= form.text_field :address, class:"form-control" %>
    </p>
    <p>
      <%= form.label :image, t("image") %>
      <%= form.file_field :image %>
    </p>
    <p>
      <%= form.submit t("create_hotel"), class: "btn btn-primary" %>
    </p>

  <% end %>
    </div>
  </div>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>
<h3>Hotel Details</h3>
<p>
  <strong>name:</strong>
  <%= @hotel.name %>
</p>
<p>
  <strong>starLevel:</strong>
  <%= @hotel.starLevel %>
</p>
<p>
  <strong>address:</strong>
  <%= @hotel.address %>
</p>
<p>
  <strong>description:</strong>
  <%= @hotel.description %>
</p>

<p>
  <strong>
  <%= image_tag @hotel.image.to_s, alt: "ks1", width: "100%", id: "ks1" %>
  </strong>
</p>

app/views/rooms/_error.html.erb
<% if @room.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "The form contains" %> <%= pluralize @room.errors.count, "error" %>.
    </div>
    <ul>
    <% @room.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<%= form_with(model: @room, local: true) do |form| %>
  <%= render 'error' %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name, class:"form-control" %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description, :value => @room.description, class:"form-control" %>
    </p>
    <p>
      <%= form.label :hotel %><br>
      <%= select("room", "hotel_id", Hotel.all.collect {|c| [ c.name, c.id ] }, {prompt: 'Select ', selected: '', disabled: ''}) %>
    </p>
    <p>
      <%= form.label :room_type %><br>
      <%= select("room", "room_type_id", RoomType.all.collect {|c| [ c.name, c.id ] }, {prompt: 'Select room_type', selected: '', disabled: ''}) %>
    </p>
    <p>
      <%= form.label :status %><br>
      <%= form.text_field :status, class:"form-control" %>
    </p>
    <p>
      <%= form.label :image %>
      <%= form.file_field :image %>
      <%= image_tag @room.image.to_s, class:'fixsize' %>
    </p>

    <p>
      <%= form.submit  "update", class: "btn btn-primary" %>
    </p>

  <% end %>
    </div>
  </div>

  <%= link_to 'Back', root_path %>

app/views/rooms/index.html.erb
<%= link_to t("new_room"), new_room_path %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= t "room_name" %></th>
      <th scope="col"><%= t "description" %></th>
      <th scope="col"><%= t "hotel" %></th>
      <th scope="col"><%= t "room_type" %></th>
      <th scope="col"><%= t "status" %></th>
      <th scope="col"><%= t "image" %></th>
    </tr>
  </thead>
  <tbody>
    <% @room.each do |t| %>
    <tr>
      <td><%= t.name %></td>
      <td><%= t.description %></td>
      <td><%= t.hotel_id %></td>
      <td><%= t.room_type_id %></td>
      <td><%= t.status %></td>
      <td><%= image_tag t.image_url.to_s, class:"fixsize" %></td>
      <td>
        <%= link_to t("edit"), edit_room_path(t), class:"btn btn-primary" %>
        <%= link_to t("delete"), room_path(t), class:"btn btn-danger",
              method: :delete, data: { confirm: t("you_sure") } %>
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/rooms/new.html.erb
<!-- <div class="jumbotron">
  <p class="display text-center">New Room</p>
</div> -->
<% provide :title, t("new_room") %>
<h1><%= t "new_room" %></h1>
<p>
<%= form_with scope: :room, url: rooms_path, local: true do |form| %>
  <%= render 'error' %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <p>
      <%= form.label :name, t("room_name") %><br>
      <%= form.text_field :name, class:"form-control" %>
    </p>
    <p>
      <%= form.label :description, t("description") %><br>
      <%= form.text_area :description, class:"form-control"%>
    </p>
    <p>
      <%= form.label :hotel, t("hotel") %><br>
      <%= select("room", "hotel_id", Hotel.all.collect {|c| [ c.name, c.id ] }, {prompt: 'Select ', selected: '', disabled: ''}) %>
    </p>
    <p>
      <%= form.label :room_type, t("room_type") %><br>
      <%= select("room", "room_type_id", RoomType.all.collect {|c| [ c.name, c.id ] }, {prompt: 'Select room_type', selected: '', disabled: ''}) %>
    </p>
    <p>
      <%= form.label :status, t("status") %><br>
      <%= form.text_field :status, class:"form-control" %>
    </p>
    <p>
      <%= form.label :image, t("image") %>
      <%= form.file_field :image %>
    </p>
    <p>
      <%= form.submit t("create_room"), class: "btn btn-primary" %>
    </p>

  <% end %>
    </div>
  </div>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<h3>room Details</h3>
<p>
  <strong>name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>hotel_id:</strong>
  <%= @room.hotel_id %>
</p>

<p>
  <strong>room_type:</strong>
  <%= @room.room_type %>
</p>

<p>
  <strong>status:</strong>
  <%= @room.status %>
</p>

<p>
  <strong>
  <%= image_tag @room.image.to_s, width: "100%" %>
  </strong>
</p>

app/views/show_room/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= t "room_name" %></th>
      <th scope="col"><%= t "description" %></th>
      <!-- <th scope="col">Status</th> -->
      <th scope="col"><%= t "image" %></th>
    </tr>
  </thead>
  <tbody>
    <% @room.each do |t| %>
    <tr>
      <td><%= t.name %></td>
      <td><%= t.description %></td>
      <!-- <td><%= t.status %></td> -->
      <td><%= image_tag t.image_url.to_s, class:"fixsize" %></td>
      <td>
        <%= link_to t("Đặt phòng"), "#", class:"btn btn-success" %>
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/users/new.html.erb
<% provide :title, t("sign_up") %>
<h1><%= t "sign_up" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, url: signup_path do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :fullname, t("fullname") %>
      <%= f.text_field :fullname, class: "form-control" %>

      <%= f.label :address, t("address") %>
      <%= f.text_field :address, class: "form-control" %>

      <%= f.label :telephone, t("telephone") %>
      <%= f.text_field :telephone, class: "form-control" %>

      <%= f.label :email, t("email") %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, t("pass") %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t("confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>