config/routes.rb
Rails.application.routes.draw do
  get 'books/_error'
  get 'books/edit'
  get 'books/index'
  get 'books/new'
  get 'books/show'
  get 'show_room/index'
  get 'sessions/new'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get  "/help", to: "static_pages#help"
    get  "/contact", to: "static_pages#contact"
    get  "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get  "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :hotels
    resources :rooms
    get "/show_room", to: "show_room#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :room_types
  validates :name, presence: true
  validates :starLevel, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :room_type
  has_many :comments
  validates :name, presence: true

  mount_uploader :image, ImageUploader
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  belongs_to :hotel
  has_many :rooms
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :comments

  before_save :email_downcase
  validates :fullname, presence: true,
            length: {maximum: Settings.max_length_name}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            length: {maximum: Settings.max_length_email},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :password, presence: true,
            length: {minimum: Settings.min_length_pass}

  has_secure_password

  private
  def email_downcase
    email.downcase!
  end

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def _error
  end

  def edit
  end

  def index
  end

  def new
  end

  def show
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :find_hotel_id, only: %i(edit show update destroy)

  def index
    @hotel = Hotel.all
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new hotel_params

    if @hotel.save
      redirect_to hotels_url
    else
      render :new
    end
  end

  def show; end

  def update
    if @hotel.update(hotel_params)
      redirect_to @hotel
    else
      render :edit
    end
  end

  def destroy
    if @hotel.destroy
      flash[:success] = t "hotel_delete"
      redirect_to hotels_url
    else
      flash[:danger] = t "delete_fail"
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit :name, :starLevel, :address, :description, :image
  end

  def find_hotel_id
    @hotel = Hotel.find_by id: params[:id]

    return if @hotel
    flash[:danger] = t "not_found"
    redirect_to root_url
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_room_id, only: %i(edit show update destroy)

  def index
    @room = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new room_params

    if @room.save
      redirect_to rooms_url
    else
      render :new
    end
  end

  def show; end

  def update
    if @room.update(room_params)
      redirect_to @room
    else
      render :edit
    end
  end

  def destroy
    if @room.destroy
      flash[:success] = t "room_delete"
      redirect_to rooms_url
    else
      flash[:danger] = t "delete_fail"
    end
  end

  private

  def room_params
    params.require(:room).permit :name, :hotel_id, :status, :room_type_id, :description, :image
  end

  def find_room_id
    @room = Room.find_by id: params[:id]

    return if @room
    flash[:danger] = t "not_found"
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = t "danger"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/show_room_controller.rb
class ShowRoomController < ApplicationController
  def index
    @id_hotel = params[:id]
    @room = Room.where(hotel_id: @id_hotel)
    # @room = Room.all

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      log_in @user
      flash[:success] = t "welcome"
      redirect_to @user
    else
      flash[:danger] = t "error_signup"
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])

    return redirect_to root_path if @user
    flash[:danger] = t "error_find_user"
    redirect_to signup_path
  end

  private

  def user_params
    params.require(:user).permit :fullname, :address, :telephone, :email,
     :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t ".hotel_ma"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/show_room_helper.rb
module ShowRoomHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to image_tag("logo.jpg", alt: "logo", :size => "40x40"), root_path, id: "logo" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("contact"), contact_path %></li>
      <li><%= link_to t("help"), help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<style type="text/css">
  div#menu div {
    height: 100% !important;
  }
</style>
<header class="navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="row" id="menu">
      <div class="col-sm-1">
        <%= link_to image_tag("logo.jpg", alt: "logo", :size => "40x40"), root_path, id: "logo" %>
      </div>
      <div class="col-sm-3" id="search-menu">
        <form action="#" style="padding-top: 9px">
          <input class="form-control" type="text" id="search" style="width: 83%; display: inline-block;">
          <button class="btn btn-link search-btn" style="width: 15%; display: inline-block;">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </form>
      </div>

      <div class="col-sm-8">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t("home"), root_path %></li>
          <li><%= link_to t("hotel"), hotels_path %></li>
          <li><%= link_to t("room"), rooms_path %></li>
          <li><%= link_to t("sign_up"), signup_path %></li>
          <% if logged_in? %>
            <li><%= link_to t("users"), '#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t "account" %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("profile"), current_user %></li>
                <li><%= link_to t("settings"), '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t("log_out"), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t("log_in"), login_path %></li>
          <% end %>
          <li><%= link_to image_tag("en.jpg", alt: "en", :size => "30x20"), locale: "en" %></li>
          <li><%= link_to image_tag("vn.jpg", alt: "vn", :size => "30x20"), locale: "vi" %></li>

        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t "hotel_ma" %></title>
    <%= render "layouts/shim" %>
    <%= render "layouts/rails_default" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "form_contains" %> <%= pluralize @user.errors.count, "error" %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>